Month 9/step 1
lighterboiii/stellar-burgers pull request #5
Opened 2023-02-06 15:53 UTC by lighterboiii

2023-02-06 17:07 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно исправить ошибки в консоли: <https://disk.yandex.com/i/FwfIKKkoaSNcng>, по кликайте по страницам, и посмотрите на возникающие ошибки в консоли;

- При перезагрузки страницы, пользователя выкидывает из профиля. Вы должны сохранять токен в куках, local storage.

- <https://disk.yandex.com/i/Ao40V1cqiJ7htw> - при загрузке страницы у вас 2 раза вызывается запрос на получение ингредиента (при выключенном strict моде), должен вызываться 1 раз)

- По чек-листу: Роуты `/login` и `/register`, `/forgot-password` и `/reset-password` недоступны авторизованным пользователям;

- Нужно запретить пользователю отправлять заказ, если он не выбрал булки: <https://disk.yandex.com/i/UIq_4ALihVj6GA>;

- Когда пользователь нажимает на войти, то ничего не происходит, нужно нажать 2 раза. <https://disk.yandex.com/i/bSz7EaFbBsXnUg>. При нажатии на кнопку войти в идеале пользователя должны перенаправлять сразу на прошлый (защищённый url), либо на главную страницу (зависит от сценария);

### **Сделает код лучше:**

- Лучше реализовать следующий способ обновления токена) он более масштабируемый и его очень легко переиспользовать) 

  ```js
  export const fetchWithRefresh = async (url, options) => {
    try {
      const res = await fetch(url, options);
      return await checkReponse(res);
    } catch (err) {
      if (err.message === "jwt expired") {
        const refreshData = await refreshToken();
        if (!refreshData.success) {
          Promise.reject(refreshData);
        }
        localStorage.setItem("refreshToken", refreshData.refreshToken);
        setCookie("accessToken", refreshData.accessToken);
        options.headers.authorization = refreshData.accessToken;
        const res = await fetch(url, options);
        return await checkReponse(res);
      } else {
        return Promise.reject(err);
      }
    }
  };
  ```

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-02-06 17:07 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +      dispatch(deleteAllIngredients(selectedIngredients));
**Можно лучше:**

Думаю лучше вынести этот диспатч из условия)) т.к. он и там и там есть

2023-02-06 17:07 UTC, ArslanMustafin commented on src/components/ProtectedRoute/ProtectedRoute.jsx
> +}
**Можно лучше:**

Немного не понимаю в чём разница) точнее разницу вижу, но не понимаю, зачем делать отдельный роут. `authRoute`

2023-02-06 17:07 UTC, ArslanMustafin commented on src/pages/profile/profile.jsx
> +  const [passwordValue, setPasswordValue] = useState('');
**Можно лучше**

Можно сделать универсальный кастомный хук для контроля любого количества инпутов в любых формах:

```js
export function useForm(inputValues) {
  const [values, setValues] = useState(inputValues);

  const handleChange = event => {
    const { value, name } = event.target;
    setValues({ ...values, [name]: value });
  };
  return { values, handleChange, setValues };
}
```

Этот код помещают в отдельный файл useForm.js в папке hooks и импортируют функцию туда, где нужно контролировать инпуты

И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:

```js
const { values, handleChange, setValues } = useForm({...});
```

2023-02-06 17:07 UTC, ArslanMustafin commented on src/pages/profile/profile.jsx
> +        <form className={styles.form} onSubmit={onFormSubmit}>
**Вы молодец:**

Вы правильно повесели обработчик событий на форму)) многие по ошибке вешают обработчик на событие `onClick` кнопки.

2023-02-08 16:52 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

Все замечания с прошлого ревью были исправлены.

### **Вы молодец!** 🔥

### **Но есть пару небольших замечаний, которые нужно исправить:**

- Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали).

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/-HF_Z0vBlKgaUA>;

2023-02-10 09:49 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Практически все замечания были исправлены.

### **Сделает код лучше:**

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/8tscx6BHQZjGhg>;

2023-02-10 09:50 UTC, lighterboiii commented
Про начало и конец только сейчас заметил 🤦‍♂️
Исправлю)

2023-02-10 09:54 UTC, merged